output_dir: "./output/sdxl_controlnet_canny"
training: "sdxl_controlnet"
train_shards: "pipe:aws s3 cp s3://muse-datasets/laion-aesthetic6plus-min512-data/{00000..01210}.tar -"
controlnet_type: "inpainting"

mixed_precision: fp16
batch_size: 4

proportion_empty_prompts: 0.5

validation_steps: 500
checkpointing_steps: 1000
validation_images:
- ./validation_data/person_jumping.png
# - ./validation_data/person_running.png
# - ./validation_data/person_standing_with_arms_crossed.png
# - ./validation_data/person_sitting_on_bench.png
validation_prompts:
- "superman"
- "spiderman"
- "elon musk"
- "jerry seinfeld"
num_validation_images: 1
