output_dir: "./output/sdxl_controlnet_inpaint_dummy_data"
training: "sdxl_controlnet"
train_shards: "pipe:aws s3 cp s3://muse-datasets/laion-aesthetic6plus-min512-data/{00000..01210}.tar -"
controlnet_type: "inpainting"

mixed_precision: fp16
batch_size: 4
learning_rate: 0.00001
max_train_steps: 200000

proportion_empty_prompts: 0.5

validation_steps: 1000
checkpointing_steps: 5000
validation_images:
- ./validation_data/two_birds_on_branch.png
validation_prompts:
- "two birds on a branch"
num_validation_images: 1
checkpoints_total_limit: 30

project_name: "sdxl_controlnet_inpaint_dummy_data"
training_run_name: "sdxl_controlnet_inpaint_dummy_data"

dummy_dataset: True

resume_from: './output/sdxl_controlnet_inpaint_dummy_data/checkpoint-1400'
start_step: 1400