output_dir: "./output/sdxl_t2i_openpose"
training: "sdxl_adapter"
train_shards: "pipe:aws s3 cp s3://muse-datasets/laion-aesthetic6plus-min512-data/{00000..01210}.tar -"
adapter_type: "openpose"

mixed_precision: fp16
batch_size: 6

proportion_empty_prompts: 0.5

validation_steps: 300
checkpointing_steps: 100
validation_images:
- ./validation_data/person_jumping.png
# - ./validation_data/person_running.png
# - ./validation_data/person_standing_with_arms_crossed.png
# - ./validation_data/person_sitting_on_bench.png
validation_prompts:
- "superman"
# - "spiderman"
# - "elon musk"
# - "jerry seinfeld"
num_validation_images: 1

resume_from: ./output/sdxl_t2i_openpose/checkpoint-900
start_step: 900