output_dir: "./output/sdxl_controlnet_inpaint"
training: "sdxl_controlnet"
train_shards: "pipe:aws s3 cp s3://muse-datasets/laion-aesthetic6plus-min512-data/{00000..01210}.tar -"
controlnet_type: "inpainting"

mixed_precision: fp16
batch_size: 7
learning_rate: 0.00001

proportion_empty_prompts: 0.5

validation_steps: 1000
checkpointing_steps: 1000
validation_images:
- ./validation_data/person_jumping.png
- ./validation_data/bright_room_with_chair.png
- ./validation_data/couple_sitting_on_bench_infront_of_lake.png
- ./validation_data/house_in_snowy_mountains.png
- ./validation_data/hq_woman.png
- ./validation_data/man_skating.png
- ./validation_data/painting_of_rice_paddies.png
- ./validation_data/tornado_at_sea.png
- ./validation_data/two_birds_on_branch.png
validation_prompts:
- "superman"
- "bright room with chair"
- "couple sitting on bench infront of lake"
- "house in snowy mountains"
- "a beautiful woman"
- "a man skating in brooklyn"
- "a painting of people working the rice paddies"
- "a tornado in ohio"
- "two birds on a branch"
num_validation_images: 1
checkpoints_total_limit: 30

project_name: "sdxl_controlnet_inpaint"
training_run_name: "sdxl_controlnet_inpaint"

overrides:
  9_14_resume_from_1000_lr_1e-6:
    learning_rate: 0.000001
    resume_from: /fsx/william/diffusers-utils/output/sdxl_controlnet_inpaint_checkpoint_1000
    start_step: 1000
    output_dir: "./output/sdxl_controlnet_inpaint_resume_from_1000_lr_1e-6"
    training_run_name: 9_14_resume_from_1000_lr_1e-6
  
  9_14_resume_from_1000_lr_3e-6:
    learning_rate: 0.000003
    resume_from: /fsx/william/diffusers-utils/output/sdxl_controlnet_inpaint_checkpoint_1000
    start_step: 1000
    output_dir: "./output/sdxl_controlnet_inpaint_resume_from_1000_lr_3e-6"
    training_run_name: 9_14_resume_from_1000_lr_3e-6

  9_14_resume_from_1000_lr_5e-6:
    learning_rate: 0.000005
    resume_from: /fsx/william/diffusers-utils/output/sdxl_controlnet_inpaint_checkpoint_1000
    start_step: 1000
    output_dir: "./output/sdxl_controlnet_inpaint_resume_from_1000_lr_5e-6"
    training_run_name: 9_14_resume_from_1000_lr_5e-6

  9_14_resume_from_1000_lr_7e-6:
    learning_rate: 0.000007
    resume_from: /fsx/william/diffusers-utils/output/sdxl_controlnet_inpaint_checkpoint_1000
    start_step: 1000
    output_dir: "./output/sdxl_controlnet_inpaint_resume_from_1000_lr_7e-6"
    training_run_name: 9_14_resume_from_1000_lr_7e-6

  9_15_resume_from_27000:
    resume_from: /fsx/william/diffusers-utils/output/sdxl_controlnet_inpaint/checkpoint-27000
    start_step: 27000
    output_dir: "./output/sdxl_controlnet_inpaint_9_15_resume_from_27000"
    training_run_name: 9_15_resume_from_27000

  9_15_resume_from_27000_lr_5e-5:
    resume_from: /fsx/william/diffusers-utils/output/sdxl_controlnet_inpaint/checkpoint-27000
    start_step: 27000
    output_dir: "./output/sdxl_controlnet_inpaint_9_15_resume_from_27000_lr_5e-5"
    training_run_name: 9_15_resume_from_27000_lr_5e-5